# Generated by Django 3.2 on 2021-04-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time of the event'),
        ),
        migrations.AlterField(
            model_name='eventtime',
            name='from_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time of the event'),
        ),
    ]
